src/ProjetoAppLivros/Models/ErrorViewModel.cs
namespace ProjetoAppLivros.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/ProjetoAppLivros/Models/Livro.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace ProjetoAppLivros.Models
{
    /// <summary>
    /// Classe responsável por representar a entidade de modelo Livro.
    /// </summary>
    public class Livro
    {
        /// <value>Propriedade responsável por representar o id.</value>
        public int Id { get; set; }

        /// <value>Propriedade responsável por atribuir o título.</value>
        [Display(Name = "Título")]
        [Required]
        public string Titulo { get; set; }
        
        /// <value>Propriedade responsável por informar o autor.</value>
        [Display(Name = "Autor")]
        [Required]
        public string Autor { get; set; }
        
        /// <value>Propriedade responsável por informar o gênero.</value>
        [Display(Name = "Gênero")]
        [Required]
        public string Genero { get; set; }

        /// <value>Propriedade responsável por atribuir a data de lançamento.</value>
        [Display(Name = "Ano de Lançamento")]
        [Required]
        public DateTime Lancamento { get; set; }

        /// <value>Propriedade responsável por informar o gênero do livro</value>
        [Display(Name = "Editora")]
        [Required]
        public string Editora { get; set; }
    }
}

src/ProjetoAppLivros/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ProjetoAppLivros.Models;

namespace ProjetoAppLivros.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

src/ProjetoAppLivros/Controllers/LivrosController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjetoAppLivros.Context;
using ProjetoAppLivros.Models;

namespace ProjetoAppLivros.Controllers
{
    /// <summary>
    /// Controlador responsável pelas actions referentes a entidade Livro.
    /// </summary>
    public class LivrosController : Controller
    {
        /// <value>Propriedade de referência para o DbContext.</value>
        private readonly ProjetoAppLivrosDbContext _context;

        /// <summary>
        /// Construtor sobrescrito para a inicialização do DbContext.
        /// </summary>
        /// <param name="context">Parâmtro referente ao DbContex.</param>
        public LivrosController(ProjetoAppLivrosDbContext context)
        {
            _context = context;
        }

        
        /// <summary>
        /// Action responsável pela listagem dos livros cadastrados.
        /// </summary>
        /// <returns>View com lista de livros inseridos.</returns>
        public async Task<IActionResult> Index(string titulo)
        {
            var livros = from l in _context.Livros select l;

            if(!String.IsNullOrEmpty(titulo))
            {
                livros = livros.Where(l => l.Titulo.Contains(titulo));
            }

            return View(await livros.ToListAsync());
        }

        /// <summary>
        /// Action responsável pela exibição dos detalhes de um livro.
        /// </summary>
        /// <param name="id">Identifica o registro a ser detalhado.</param>
        /// <returns>View com com detalhes de livro.</returns>
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        /// <summary>
        /// Action responsável por direcionar registro do livro inserido.
        /// </summary>
        /// <returns>View com lista de livros.</returns>
        public IActionResult Create()
        {
            return View();
        }

        /// <summary>
        /// Action responsável pela criação de novos registros dos livros.
        /// </summary>
        /// <returns>View com novo registro criado na lista de livros.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Titulo,Autor,Genero,Lancamento,Editora")] Livro livro)
        {
            if (ModelState.IsValid)
            {
                _context.Add(livro);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(livro);
        }

        /// <summary>
        /// Action responsável por direcionar registro do livro editado.
        /// </summary>
        /// <param name="id">Identifica o registro a ser editado.</param>
        /// <returns>View atualizada com lista de livros.</returns>
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livros.FindAsync(id);
            if (livro == null)
            {
                return NotFound();
            }
            return View(livro);
        }

        /// <summary>
        /// Action responsável pela edição de registro do livro.
        /// </summary>
        /// <param name="id">Usado para referenciar a entidade Livro.</param>
        /// <returns>View com registro editado na lista de livros.</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Titulo,Autor,Genero,Lancamento,Editora")] Livro livro)
        {
            if (id != livro.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(livro);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LivroExists(livro.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(livro);
        }

        /// <summary>
        /// Action responsável pela exclusão de livro.
        /// </summary>
        /// <param name="id">Identifica o registro a ser excluído.</param>
        /// <returns>View com registro da lista de livros.</returns>
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var livro = await _context.Livros
                .FirstOrDefaultAsync(m => m.Id == id);
            if (livro == null)
            {
                return NotFound();
            }

            return View(livro);
        }

        /// <summary>
        /// Action responsável pela confirmação da exclusão de livro.
        /// </summary>
        /// <param name="id">Identifica o registro a ser confirmada a exclusão.</param>
        /// <returns>View atualizada com lista de livros após a exclusão.</returns>
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var livro = await _context.Livros.FindAsync(id);
            _context.Livros.Remove(livro);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        /// <summary>
        /// Action responsável verificar se registro de livro existe.
        /// </summary>
        /// <param name="id">Parâmetro de pesquisa do livro.</param>
        /// <returns>Registro do livro.</returns>
        private bool LivroExists(int id)
        {
            return _context.Livros.Any(e => e.Id == id);
        }
    }
}

src/ProjetoAppLivros/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="jumbotron p-4 p-md-5 text-white rounded bg-dark">
    <div class="col-md-6 px-0">
      <h1 class="display-4 font-italic">ProjetoAppLivros</h1>
      <p class="lead my-3">Aplicação para manipular registro em banco de dados, 
          com operações básicas de inclusão, atualização, pesquisa e exclusão
          de lista de livros.</p>
    </div>
</div>

src/ProjetoAppLivros/Views/Livros/Create.cshtml
@model ProjetoAppLivros.Models.Livro

@{
    ViewData["Title"] = "Create";
}

<h1>Adicionar</h1>

<h4>Livro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input id="livroTitulo" asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input id="livroAutor" asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input id="livroGenero" asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lancamento" class="control-label"></label>
                <input id="livroLancamento" asp-for="Lancamento" class="form-control" />
                <span asp-validation-for="Lancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editora" class="control-label"></label>
                <input id="livroEditora" asp-for="Editora" class="form-control" />
                <span asp-validation-for="Editora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="ADICIONAR" class="btn btn-success" />
                <button id="limparCampos" class="btn btn-outline-dark" onclick="limparCamposCriacao()">CANCELAR</button>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">lista de Livros</a>
</div>

@section Scripts {
    <script src="~/js/site.js" asp-append-version="true"></script>
}

src/ProjetoAppLivros/Views/Livros/Delete.cshtml
@model ProjetoAppLivros.Models.Livro

@{
    ViewData["Title"] = "Delete";
}

<h1>Excluir</h1>

<h3>Você tem certeza que deseja excluir este livro?</h3>
<div>
    <h4>Livro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Editora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Editora)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="EXCLUIR" class="btn btn-danger" /> |
        <a asp-action="Index">lista de Livros</a>
    </form>
</div>

src/ProjetoAppLivros/Views/Livros/Details.cshtml
@model ProjetoAppLivros.Models.Livro

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes</h1>

<div>
    <h4>Livro</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Titulo)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Autor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Autor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Genero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lancamento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lancamento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Editora)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Editora)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Editar</a> |
    <a asp-action="Index">lista de Livros</a>
</div>

src/ProjetoAppLivros/Views/Livros/Edit.cshtml
@model ProjetoAppLivros.Models.Livro

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar</h1>

<h4>Livro</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Titulo" class="control-label"></label>
                <input asp-for="Titulo" class="form-control" />
                <span asp-validation-for="Titulo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Autor" class="control-label"></label>
                <input asp-for="Autor" class="form-control" />
                <span asp-validation-for="Autor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Genero" class="control-label"></label>
                <input asp-for="Genero" class="form-control" />
                <span asp-validation-for="Genero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Lancamento" class="control-label"></label>
                <input asp-for="Lancamento" class="form-control" />
                <span asp-validation-for="Lancamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Editora" class="control-label"></label>
                <input asp-for="Editora" class="form-control" />
                <span asp-validation-for="Editora" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="SALVAR" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">lista de Livros</a>
</div>

src/ProjetoAppLivros/Views/Livros/Index.cshtml
@model IEnumerable<ProjetoAppLivros.Models.Livro>

@{
    ViewData["Title"] = "Index";
}

<h1>Início</h1>

<p>
    <a asp-action="Create">Adicionar Novo Livro</a>
</p>

<form asp-controller="Livros" asp-action="Index" class="form-inline">
    <p>
        Título: <input type="text" name="titulo" id="pesquisarLivro" class="form-control">
        <input type="submit" id="pesquisar" value="PESQUISAR" class="btn btn-info" onclick="validarCampoPesquisa()" />
        <button id="limparCampo" class="btn btn-outline-dark" onclick="limparCampoPesquisa()">CANCELAR</button>
    </p>
</form>

<table class="table table-striped table-light table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Titulo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Autor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Genero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Lancamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Editora)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Autor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Genero)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Lancamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Editora)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Excluir</a>
            </td>
        </tr>
}
    </tbody>
</table>

@section Scripts {
    <script src="~/js/site.js" asp-append-version="true"></script>
}

src/ProjetoAppLivros/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoAppLivros</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ProjetoAppLivros</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Início</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Livros" asp-action="Index">Livros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - Desenvolvido por Paulo Alves - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacidade</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>